Add build.bat
Builds, but shadercross fails to compile :
C:\dev\howprice\SDL_shadercross_build>bin\shadercross shaders\test.vert.hlsl -s hlsl -d dxil -t vertex -e "main" -o bin\test.vert.dxil
ERROR: Failed to compile DXIL from HLSL: HLSL compilation failed: SPIR-V CodeGen not available. Please recompile with -DENABLE_SPIRV_CODEGEN=ON.

I don't know why this is because the build is configured with -DENABLE_SPIRV_CODEGEN=ON